## DESCRIPTION:
## mk module for the detection of structural variants (SVs), using BAM type of data. 
## The script uses Delly to detect SVs from a BAM file.
## 
## USAGE:
## Alternative 1: Single target execution.
##	`mk <SPECIFIC_TARGET>`; where SPECIFIC_TARGET is any line printed by the `/bin/create-targets` script in this module.
##
## Alternative 2: Multiple target tandem execution.
##	`bin/targets | xargs mk` 
##
## AUTHOR:
##	Karla Lozano (klg1219sh@gmail.com), for Winter Genomics (http://www.wintergenomics.com/) - 2018

MKSHELL=/bin/bash

# Load configurations form file
< config.mk

## Call SV from single bam file
results/%.delly_call.bcf: data/%.bam
	set -x
	mkdir -p $(dirname $target)
	$DELLY call \
		-o $target.build \
		-g $REF \
		$prereq \
	&& mv $target.build $target \
	&& mv $target.build.csi $target.csi

### Add a "clean" recipe to quickly remove results directory
clean:V:
	rm -r results/
